import { describe, expect, it } from "vitest";

import {
  LEARNING_PROVIDER_WARNING_BODY,
  shouldShowLearningProviderWarning,
} from "./learning-provider-warning";

describe("learning provider warning", () => {
  it("renders the canonical warning body", () => {
    expect(LEARNING_PROVIDER_WARNING_BODY).toMatchInlineSnapshot(
      `"Changing this agent's provider will stop new embeddings from being generated by the previous provider. The agent's existing memories stay searchable via full-text search (no semantic similarity), and new memories saved after this change will use the new provider. Memories created with two providers cannot be ranked against each other on similarity - only on text match."`,
    );
  });

  it("shows only when learning is enabled, embedded memories exist, and provider changes", () => {
    expect(
      shouldShowLearningProviderWarning({
        learningEnabled: true,
        hasEmbeddedMemories: true,
        fromProvider: "openai",
        toProvider: "anthropic",
      }),
    ).toBe(true);
  });

  it("does not show when learning is disabled or the store has no embeddings", () => {
    expect(
      shouldShowLearningProviderWarning({
        learningEnabled: false,
        hasEmbeddedMemories: true,
        fromProvider: "openai",
        toProvider: "anthropic",
      }),
    ).toBe(false);
    expect(
      shouldShowLearningProviderWarning({
        learningEnabled: true,
        hasEmbeddedMemories: false,
        fromProvider: "openai",
        toProvider: "anthropic",
      }),
    ).toBe(false);
  });

  it("does not show when the selected provider is unchanged", () => {
    expect(
      shouldShowLearningProviderWarning({
        learningEnabled: true,
        hasEmbeddedMemories: true,
        fromProvider: "openai",
        toProvider: "openai",
      }),
    ).toBe(false);
  });
});
