export const LEARNING_PROVIDER_WARNING_BODY =
  "Changing this agent's provider will stop new embeddings from being generated by the previous provider. The agent's existing memories stay searchable via full-text search (no semantic similarity), and new memories saved after this change will use the new provider. Memories created with two providers cannot be ranked against each other on similarity - only on text match.";

type ProviderWarningInput = {
  learningEnabled: boolean;
  hasEmbeddedMemories: boolean;
  fromProvider?: string | null;
  toProvider?: string | null;
};

function normalizeProvider(provider?: string | null) {
  const trimmed = provider?.trim();
  return trimmed ? trimmed : null;
}

export function shouldShowLearningProviderWarning({
  learningEnabled,
  hasEmbeddedMemories,
  fromProvider,
  toProvider,
}: ProviderWarningInput) {
  const currentProvider = normalizeProvider(fromProvider);
  const nextProvider = normalizeProvider(toProvider);
  return (
    learningEnabled &&
    hasEmbeddedMemories &&
    Boolean(currentProvider) &&
    Boolean(nextProvider) &&
    currentProvider !== nextProvider
  );
}
