#!/usr/bin/env bash
set -euo pipefail

generated_path="packages/supabase-schema/src/database.types.ts"
legacy_path="supabase/generated/database.types.ts"
header='// Generated by `pnpm run db:schema:sync`. Do not edit by hand.'

if [ -e "$legacy_path" ]; then
  echo "$legacy_path must not exist. Platform consumes $generated_path." >&2
  exit 1
fi

if [ ! -f "$generated_path" ]; then
  echo "Missing generated DB types: $generated_path" >&2
  exit 1
fi

first_line="$(sed -n '1p' "$generated_path")"
if [ "$first_line" != "$header" ]; then
  cat >&2 <<EOF
database_schema_drift_detected:
  artifact: $generated_path
  owning_artifact: scripts/sync-supabase-schema.mjs
  constraint: generated_types_header
  expected_value: $header
  offending_value: $first_line

$generated_path must start with:
$header

Regenerate it with: pnpm run db:schema:sync
EOF
  exit 1
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  exit 0
fi

base_ref="${CONTRACT_GUARD_BASE_REF:-}"
if [ -z "$base_ref" ] && [ -n "${GITHUB_BASE_REF:-}" ]; then
  base_ref="origin/${GITHUB_BASE_REF}"
fi
if [ -z "$base_ref" ] && git rev-parse --verify origin/main >/dev/null 2>&1; then
  base_ref="origin/main"
fi
if [ -z "$base_ref" ] && git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
  base_ref="HEAD~1"
fi
if [ -z "$base_ref" ]; then
  exit 0
fi

merge_base="$(git merge-base HEAD "$base_ref" 2>/dev/null || true)"
if [ -z "$merge_base" ]; then
  exit 0
fi

changed_files="$(git diff --name-only "$merge_base"...HEAD)"
if ! printf '%s\n' "$changed_files" | grep -Fx "$generated_path" >/dev/null; then
  exit 0
fi

non_header_generated_changes="$(
  git diff --unified=0 "$merge_base"...HEAD -- "$generated_path" |
    awk -v header="$header" '
      /^diff --git / || /^index / || /^--- / || /^\+\+\+ / || /^@@ / { next }
      /^[+-]/ {
        line = substr($0, 2)
        if (line != header && line != "") {
          print
        }
      }
    '
)"

if [ -z "$non_header_generated_changes" ]; then
  exit 0
fi

cat >&2 <<EOF
database_schema_change_detected:
  artifact: $generated_path
  owning_artifact: harper-server/supabase/migrations/
  constraint: generated_types_freshness
  expected_value: generated DB type changes come from the configured Supabase project
  offending_value: generated DB type changes in Platform PR

$generated_path changed in this Platform PR.

Generated DB type changes must come from schema changes:
1. Add or update a migration in harper-server/supabase/migrations/.
2. Apply it to the intended Supabase project.
3. Run pnpm run db:schema:sync.
4. Run pnpm run db:schema:check for structured schema, extension, and critical constraint diagnostics.

Do not hand-edit generated DB type files.

This guard does not reject regenerated type diffs by itself. Freshness is
validated by pnpm run db:schema:check when live Supabase credentials are
available in CI.
EOF
